apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: insta-clone-frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: azure-application-gateway
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: insta-clone-frontend-service-expose
            port:
              number: 3000

