apiVersion: v1
kind: Service
metadata:
  name: insta-clone-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: insta-clone-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000